services:
  - type: web
    name: artists-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    envVars:
      - key: PORT
        value: 8000
